eventprowl/eventprowl/src/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

""" Custom files """
from responses import get_events, get_all_events, remove_event, \
	get_user_messages, create_event, create_gallery, create_photo, \
	remove_photo, remove_gallery, get_galleries, update_event_details, \
	update_user
	
from views import main, login, signup, help, galleries, events_view, \
	messages_widget, event_short_template, observer_profile, \
	organisator_profile, main_layout, logout

processed_partial_patterns = patterns('',
	url(r'^main$', main, name='main'),
	url(r'^login$', login, name='login'),
	url(r'^signup$', signup, name='signup'),
	url(r'^help$', help, name='help'),
	url(r'^galleries$', galleries, name='galleries'),
	url(r'^events_view$', events_view, name='events_view'),
	url(r'^messages_widget$', messages_widget, name='messages_widget'),
	url(r'^event_short_template$', event_short_template, name='event_short_template'),
	url(r'^profile/observer$', observer_profile, name='observer_profile'),
	url(r'^profile/organisator$', organisator_profile, name='organisator_profile'),
)

urlpatterns = i18n_patterns('',
	url(r'^$', main_layout, name='main_layout'),
	url(r'^messages/$', get_user_messages, name='user_messages'),
	url(r'^logout/$', logout, name='logout'),
	url(r'^processed_partials/', include(processed_partial_patterns, namespace='processed_partials')),
	url(r'^get_events/(?P<username>\w{1,50})/', get_events, name='get_events'),
	url(r'^get_all_events/', get_all_events, name='get_all_events'),
	url(r'^get_galleries/(?P<username>\w{1,50})/', get_galleries, name='get_galleries'),
	url(r'^remove_event/(?P<title>.*)/', remove_event, name='remove_event'),
	url(r'^remove_photo/(?P<id>\w{1,50})/', remove_photo, name='remove_photo'),
	url(r'^remove_gallery/(?P<id>\w{1,50})/', remove_gallery, name='remove_gallery'),
	url(r'^create_event/', create_event, name='create_event'),
	url(r'^create_gallery/', create_gallery, name='create_gallery'),
	url(r'^create_photo/', create_photo, name='create_photo'),
	url(r'^update_event_details/', update_event_details, name='update_event_details'),
	url(r'^update_user/', update_user, name='update_user'),
	(r'^photologue/', include('photologue_custom.urls')),
	url(r'^photologue/', include('photologue.urls', namespace='photologue')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "eventprowl.src.views.error404"

eventprowl/photologue/urls.py
from django.conf.urls import *
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from .views import PhotoListView, PhotoDetailView, GalleryListView, \
    GalleryDetailView, PhotoArchiveIndexView, PhotoDateDetailView, PhotoDayArchiveView, \
    PhotoYearArchiveView, PhotoMonthArchiveView, GalleryArchiveIndexView, GalleryYearArchiveView, \
    GalleryDateDetailView, GalleryDayArchiveView, GalleryMonthArchiveView, GalleryDateDetailOldView, \
    GalleryDayArchiveOldView, GalleryMonthArchiveOldView, PhotoDateDetailOldView, \
    PhotoDayArchiveOldView, PhotoMonthArchiveOldView

"""NOTE: the url names are changing. In the long term, I want to remove the 'pl-'
prefix on all urls, and instead rely on an application namespace 'photologue'.

At the same time, I want to change some URL patterns, e.g. for pagination. Changing the urls
twice within a few releases, could be confusing, so instead I am updating URLs bit by bit.

The new style will coexist with the existing 'pl-' prefix for a couple of releases.

"""


urlpatterns = patterns('',

                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           GalleryDateDetailView.as_view(month_format='%m'),
                           name='gallery-detail'),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
                           GalleryDayArchiveView.as_view(month_format='%m'),
                           name='gallery-archive-day'),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
                           GalleryMonthArchiveView.as_view(month_format='%m'),
                           name='gallery-archive-month'),
                       url(r'^gallery/(?P<year>\d{4})/$',
                           GalleryYearArchiveView.as_view(),
                           name='pl-gallery-archive-year'),
                       url(r'^gallery/$',
                           GalleryArchiveIndexView.as_view(),
                           name='pl-gallery-archive'),
                       url(r'^$',
                           RedirectView.as_view(url=reverse_lazy('photologue:pl-gallery-archive')),
                           name='pl-photologue-root'),
                       url(r'^gallery/(?P<slug>[\-\d\w]+)/$',
                           GalleryDetailView.as_view(), name='pl-gallery'),
                       url(r'^gallerylist/$',
                           GalleryListView.as_view(),
                           name='gallery-list'),

                       url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           PhotoDateDetailView.as_view(month_format='%m'),
                           name='photo-detail'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
                           PhotoDayArchiveView.as_view(month_format='%m'),
                           name='photo-archive-day'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
                           PhotoMonthArchiveView.as_view(month_format='%m'),
                           name='photo-archive-month'),
                       url(r'^photo/(?P<year>\d{4})/$',
                           PhotoYearArchiveView.as_view(),
                           name='pl-photo-archive-year'),
                       url(r'^photo/$',
                           PhotoArchiveIndexView.as_view(),
                           name='pl-photo-archive'),

                       url(r'^photo/(?P<slug>[\-\d\w]+)/$',
                           PhotoDetailView.as_view(),
                           name='pl-photo'),
                       url(r'^photolist/$',
                           PhotoListView.as_view(),
                           name='photo-list'),

                       # Deprecated URLs.
                       url(r'^gallery/page/(?P<page>[0-9]+)/$',
                           GalleryListView.as_view(),
                           {'deprecated_pagination': True},
                           name='pl-gallery-list'),
                       url(r'^photo/page/(?P<page>[0-9]+)/$',
                           PhotoListView.as_view(),
                           {'deprecated_pagination': True},
                           name='pl-photo-list'),

                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           GalleryDateDetailOldView.as_view(),
                           name='pl-gallery-detail'),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',
                           GalleryDayArchiveOldView.as_view(),
                           name='pl-gallery-archive-day'),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
                           GalleryMonthArchiveOldView.as_view(),
                           name='pl-gallery-archive-month'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           PhotoDateDetailOldView.as_view(),
                           name='pl-photo-detail'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',
                           PhotoDayArchiveOldView.as_view(),
                           name='pl-photo-archive-day'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
                           PhotoMonthArchiveOldView.as_view(),
                           name='pl-photo-archive-month')
                       )

eventprowl/photologue/views.py
import warnings

from django.conf import settings
from django.views.generic.dates import ArchiveIndexView, DateDetailView, DayArchiveView, MonthArchiveView, \
    YearArchiveView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse

from .models import Photo, Gallery

# Number of galleries to display per page.
GALLERY_PAGINATE_BY = getattr(settings, 'PHOTOLOGUE_GALLERY_PAGINATE_BY', 20)

if GALLERY_PAGINATE_BY != 20:
    warnings.warn(
        DeprecationWarning('PHOTOLOGUE_GALLERY_PAGINATE_BY setting will be removed in Photologue 3.2'))

# Number of photos to display per page.
PHOTO_PAGINATE_BY = getattr(settings, 'PHOTOLOGUE_PHOTO_PAGINATE_BY', 20)

if PHOTO_PAGINATE_BY != 20:
    warnings.warn(
        DeprecationWarning('PHOTOLOGUE_PHOTO_PAGINATE_BY setting will be removed in Photologue 3.2'))

# Gallery views.


class GalleryListView(ListView):
    queryset = Gallery.objects.on_site().is_public()
    paginate_by = GALLERY_PAGINATE_BY

    def get_context_data(self, **kwargs):
        context = super(GalleryListView, self).get_context_data(**kwargs)
        if self.kwargs.get('deprecated_pagination', False):
            warnings.warn(
                DeprecationWarning('Page numbers should now be passed via a page query-string parameter.'
                                   ' The old style "/page/n/"" will be removed in Photologue 3.2.'))
        return context


class GalleryDetailView(DetailView):
    queryset = Gallery.objects.on_site().is_public()


class GalleryDateView(object):
    queryset = Gallery.objects.on_site().is_public()
    date_field = 'date_added'
    allow_empty = True


class GalleryDateDetailView(GalleryDateView, DateDetailView):
    pass


class GalleryArchiveIndexView(GalleryDateView, ArchiveIndexView):
    pass


class GalleryDayArchiveView(GalleryDateView, DayArchiveView):
    pass


class GalleryMonthArchiveView(GalleryDateView, MonthArchiveView):
    pass


class GalleryYearArchiveView(GalleryDateView, YearArchiveView):
    make_object_list = True

# Photo views.


class PhotoListView(ListView):
    queryset = Photo.objects.on_site().is_public()
    paginate_by = PHOTO_PAGINATE_BY

    def get_context_data(self, **kwargs):
        context = super(PhotoListView, self).get_context_data(**kwargs)
        if self.kwargs.get('deprecated_pagination', False):
            warnings.warn(
                DeprecationWarning('Page numbers should now be passed via a page query-string parameter.'
                                   ' The old style "/page/n/"" will be removed in Photologue 3.2'))
        return context


class PhotoDetailView(DetailView):
    queryset = Photo.objects.on_site().is_public()


class PhotoDateView(object):
    queryset = Photo.objects.on_site().is_public()
    date_field = 'date_added'
    allow_empty = True


class PhotoDateDetailView(PhotoDateView, DateDetailView):
    pass


class PhotoArchiveIndexView(PhotoDateView, ArchiveIndexView):
    pass


class PhotoDayArchiveView(PhotoDateView, DayArchiveView):
    pass


class PhotoMonthArchiveView(PhotoDateView, MonthArchiveView):
    pass


class PhotoYearArchiveView(PhotoDateView, YearArchiveView):
    make_object_list = True


# Deprecated views.

class DeprecatedMonthMixin(object):

    """Representation of months in urls has changed from a alpha representation ('jan' for January)
    to a numeric representation ('01' for January).
    Properly deprecate the previous urls."""

    query_string = True

    month_names = {'jan': '01',
                   'feb': '02',
                   'mar': '03',
                   'apr': '04',
                   'may': '05',
                   'jun': '06',
                   'jul': '07',
                   'aug': '08',
                   'sep': '09',
                   'oct': '10',
                   'nov': '11',
                   'dec': '12', }

    def get_redirect_url(self, *args, **kwargs):
        print('a')
        warnings.warn(
            DeprecationWarning('Months are now represented in urls by numbers rather than by '
                               'their first 3 letters. The old style will be removed in Photologue 3.2.'))


class GalleryDateDetailOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(GalleryDateDetailOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:gallery-detail', kwargs={'year': kwargs['year'],
                                                            'month': self.month_names[kwargs['month']],
                                                            'day': kwargs['day'],
                                                            'slug': kwargs['slug']})


class GalleryDayArchiveOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(GalleryDayArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:gallery-archive-day', kwargs={'year': kwargs['year'],
                                                                 'month': self.month_names[kwargs['month']],
                                                                 'day': kwargs['day']})


class GalleryMonthArchiveOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(GalleryMonthArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:gallery-archive-month', kwargs={'year': kwargs['year'],
                                                                   'month': self.month_names[kwargs['month']]})


class PhotoDateDetailOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoDateDetailOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:photo-detail', kwargs={'year': kwargs['year'],
                                                          'month': self.month_names[kwargs['month']],
                                                          'day': kwargs['day'],
                                                          'slug': kwargs['slug']})


class PhotoDayArchiveOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoDayArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:photo-archive-day', kwargs={'year': kwargs['year'],
                                                               'month': self.month_names[kwargs['month']],
                                                               'day': kwargs['day']})


class PhotoMonthArchiveOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoMonthArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:photo-archive-month', kwargs={'year': kwargs['year'],
                                                                 'month': self.month_names[kwargs['month']]})

eventprowl/photologue/templates/photologue/gallery_archive.html
{% load i18n %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% trans "Latest photo galleries" %}</h1>
    </div>

	<div class="row">
	
		<aside class="col-md-2">

			<h4>{% trans "Filter by year" %}</h4>
			<ul>
			{% for date in date_list %}
				<li><a href="{% url 'photologue:pl-gallery-archive-year' date.year %}">{{ date|date:"Y" }}</a></li>
			{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">
			
			{% if latest %}
			    {% for gallery in latest %}
            {% if gallery.galleries.first.user == request.user %}
							{% include "photologue/includes/gallery_sample.html" %}
            {% endif %}
			    {% endfor %}
			{% else %}
			    <p>{% trans "No galleries were found" %}.</p>
			{% endif %}
			
		</main>

	</div>
	
{% endblock %}

eventprowl/photologue/templates/photologue/gallery_archive_day.html
{% load i18n %}

{% block title %}{% blocktrans with show_day=day|date:"d F Y" %}Galleries for {{ show_day }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_day=day|date:"d F Y" %}Galleries for {{ show_day }}{% endblocktrans %}</h1>
    </div>

    <div class="row col-lg-12">
        {% if object_list %}
            {% for gallery in object_list %}
							{% if gallery.galleries.first.user == request.user %}
								{% include "photologue/includes/gallery_sample.html" %}
							{% endif %}
            {% endfor %}
        {% else %}
            <p>{% trans "No galleries were found." %}</p>
        {% endif %}
    </div>
    
    <div><a href="{% url 'photologue:gallery-archive-month' day.year day|date:"m"|lower %}" class="btn btn-default">{% trans "View all galleries for month" %}</a></div>

{% endblock %}

eventprowl/photologue/templates/photologue/gallery_archive_month.html
{% load i18n %}

{% block title %}{% blocktrans with show_month=month|date:"F Y" %}Galleries for {{ show_month }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_month=month|date:"F Y" %}Galleries for {{ show_month }}{% endblocktrans %}</h1>
    </div>

    <div class="row">

        <aside class="col-md-2">

            <h4>{% trans "Filter by day" %}</h4>
            <ul>
            {% for date in date_list %}
                <li><a href="{% url 'photologue:gallery-archive-day' date.year date|date:"m"|lower date.day %}">{{ date|date:"d" }}</a></li>
            {% endfor %}
            </ul>

        </aside>

        <main class="col-md-10">

            {% if object_list %}
                {% for gallery in object_list %}
									{% if gallery.galleries.first.user == request.user %}
										{% include "photologue/includes/gallery_sample.html" %}
									{% endif %}
                {% endfor %}
            {% else %}
                <p>{% trans "No galleries were found." %}</p>
            {% endif %}

            <div><a href="{% url 'photologue:pl-gallery-archive-year' month.year %}" class="btn btn-default">{% trans "View all galleries for year" %}</a></div>

        </main>

    </div>

{% endblock %}

eventprowl/photologue/templates/photologue/gallery_archive_year.html
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Galleries for {{ show_year }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_year=year|date:"Y" %}Galleries for {{ show_year }}{% endblocktrans %}</h1>
    </div>

	<div class="row">

		<aside class="col-md-2">

			<h4>{% trans "Filter by month" %}</h4>
			<ul>
				{% for date in date_list %}
					<li><a href="{% url 'photologue:gallery-archive-month' date.year date|date:"m"|lower %}">{{ date|date:"F" }}</a></li>
				{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">

			{% if object_list %}
				{% for gallery in object_list %}
					{% if gallery.galleries.first.user == request.user %}
						{% include "photologue/includes/gallery_sample.html" %}
					{% endif %}
				{% endfor %}
			{% else %}
			    <p>{% trans "No galleries were found." %}</p>
			{% endif %}

		    <div><a href="{% url 'photologue:pl-gallery-archive' %}" class="btn btn-default">{% trans "View all galleries" %}</a></div>

		</main>

	</div>

{% endblock %}

eventprowl/photologue/templates/photologue/gallery_detail.html
{% load i18n %}

{% block content %}

	<div class="row col-lg-12">
        <h1 class="page-header" id="gallery-header" data-id="{{ gallery.id }}">{{ gallery.title }}</h1>
        <p class="muted"><small>{% trans "Published" %} {{ gallery.date_added }}</small></p>        
        {% if gallery.description %}{{ gallery.description|safe }}{% endif %}
       	 <div class='images-holder'>
		    {% for photo in gallery.public %}
			<a href="{{ photo.get_absolute_url }}">
				<img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
			</a>
		    {% endfor %}
	    	</div>
		<div class="btn-group btn-group-justified" role="group" aria-label="Inner gallery navigation">
			<div class="btn-group" role="group">
				<button type="button" class="btn btn-default" data-toggle="modal" data-target=".add-photo-modal"> {% trans "Add a photo" %}</button>
			</div>
			<div class="btn-group" role="group">
				<button type="button" class="btn btn-default" data-toggle="modal" data-target=".remove-gallery-modal"> {% trans "Delete gallery" %}</button>
			</div>
			<div class="btn-group" role="group">
				<a id="galleries-redirect-button" href="{% url 'photologue:pl-gallery-archive' %}" class="btn btn-default">
					{% trans "View all galleries" %}
				</a>
			</div>
		</div>
	</div>

	<div class="modal fade add-photo-modal" tabindex="-1" role="dialog" aria-labelledby="Add Photo" aria-hidden="true">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">
						<span aria-hidden="true">×</span>
						<span class="sr-only">{% trans "Close" %}</span>
					</button>
					<h4 class="modal-title"> {% trans "Add photo"  %} </h4>
				</div>
				<form target="iframe" role="form" method="post" id="photo-creation-form" action="create_photo/" autocomplete="off" enctype="multipart/form-data">
					<div class="modal-body">
						<div id="photo-creation-messages-widget-container"></div>
						{{ photo_creation_form }}
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Cancel" %}</button>
						<input id="create-photo-button" type="submit" class="btn btn-success" value="{% trans 'Create' %}"></input>
					</div>
				</form>

				<iframe name="iframe" id="iframe" style="display:none" ></iframe>
			</div> <!-- /.modal-content -->
		</div> <!-- /.modal-dialog -->
	</div> <!-- /.modal -->

	<div class="modal fade remove-gallery-modal" tabindex="-1" role="dialog" aria-labelledby="Remove Gallery" aria-hidden="true">
			<div class="modal-dialog modal-sm">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">
							<span aria-hidden="true">×</span>
							<span class="sr-only">{% trans "Close" %}</span>
						</button>
						<h4 class="modal-title"> {% trans "Remove" %} {{ gallery.title }} </h4>
					</div>
					<form target="iframe" role="form" action="remove_gallery/{{gallery.id}}/" method="post" id="gallery-removal-form" autocomplete="off">
						<div class="modal-body">
							<div id="gallery-removal-messages-widget-container"></div>
							{{ gallery_removal_form }}
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Cancel" %}</button>
							<input type="submit" class="btn btn-danger" value="{% trans 'Remove' %}"></input>
						</div>
					</form>
				</div> <!-- /.modal-content -->
			</div> <!-- /.modal-dialog -->
		</div> <!-- /.modal -->

{% endblock %}


eventprowl/photologue/templates/photologue/photo_archive.html
{% load i18n %}

{% block title %}{% trans "Latest photos" %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% trans "Latest photos" %}</h1>
    </div>

	<div class="row">
		
		<aside class="col-md-2">

			<h4>{% trans "Filter by year" %}</h4>
			<ul>
			{% for date in date_list %}
				<li><a href="{% url 'photologue:pl-photo-archive-year' date.year %}">{{ date|date:"Y" }}</a></li>
			{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">
			
			{% if latest %}
			    {% for photo in latest %}
			        <a href="{{ photo.get_absolute_url }}">
			             <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
			        </a>
			    {% endfor %}
			{% else %}
				<p>{% trans "No photos were found" %}.</p>
			{% endif %}

		</main>

	</div>

{% endblock %}



eventprowl/photologue/templates/photologue/photo_archive_day.html
{% load i18n %}

{% block title %}{% blocktrans with show_day=day|date:"d F Y" %}Photos for {{ show_day }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_day=day|date:"d F Y" %}Photos for {{ show_day }}{% endblocktrans %}</h1>
    </div>

	{% if object_list %}
		<div class="row col-lg-12">
		    {% for photo in object_list %}
		        <a href="{{ photo.get_absolute_url }}">
		             <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
		        </a>
		    {% endfor %}
		</div>
	{% else %}
		<p>{% trans "No photos were found" %}.</p>
	{% endif %}

    <div><a href="{% url 'photologue:photo-archive-month' day.year day|date:"m"|lower %}" class="btn btn-default">{% trans "View all photos for month" %}</a></div>

{% endblock %}

eventprowl/photologue/templates/photologue/photo_archive_month.html
{% load i18n %}

{% block title %}{% blocktrans with show_month=month|date:"F Y" %}Photos for {{ show_month }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_month=month|date:"F Y" %}Photos for {{ show_month }}{% endblocktrans %}</h1>
    </div>

    <div class="row">

        <aside class="col-md-2">

            <h4>{% trans "Filter by day" %}</h4>
            <ul>
            {% for date in date_list %}
                <li><a href="{% url 'photologue:photo-archive-day' date.year date|date:"m"|lower date.day %}">{{ date|date:"d" }}</a></li>
            {% endfor %}
            </ul>

        </aside>

        <main class="col-md-10">

    		{% if object_list %}
    			<div class="row col-lg-12">
    			    {% for photo in object_list %}
    			        <a href="{{ photo.get_absolute_url }}">
    			             <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
    			        </a>
    			    {% endfor %}
    			</div>
    		{% else %}
    			<p>{% trans "No photos were found" %}.</p>
    		{% endif %}

            <div><a href="{% url 'photologue:pl-photo-archive-year' month.year %}" class="btn btn-default">{% trans "View all photos for year" %}</a></div>

        </main>

    </div>
    
{% endblock %}

eventprowl/photologue/templates/photologue/photo_archive_year.html
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Photos for {{ show_year }}{% endblocktrans %}{% endblock %}


{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_year=year|date:"Y" %}Photos for {{ show_year }}{% endblocktrans %}</h1>
    </div>

	<div class="row">

		<aside class="col-md-2">

			<h4>{% trans "Filter by month" %}</h4>
			<ul>
			{% for date in date_list %}
				<li><a href="{% url 'photologue:photo-archive-month' date.year date|date:"m"|lower %}">{{ date|date:"F" }}</a></li>
			{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">

			{% if object_list %}
				<div class="row col-lg-12">
				    {% for photo in object_list %}
				        <a href="{{ photo.get_absolute_url }}">
				             <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
				        </a>
				    {% endfor %}
				</div>
			{% else %}
				<p>{% trans "No photos were found" %}.</p>
			{% endif %}

		    <div><a href="{% url 'photologue:pl-photo-archive' %}" class="btn btn-default">{% trans "View all photos" %}</a></div>

		</main>

	</div>

{% endblock %}





eventprowl/photologue/templates/photologue/root.html
{% extends "base.html" %}