eventprowl/eventprowl/src/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

""" Custom files """
from responses import get_events, get_all_events, remove_event, \
	get_user_messages, create_event, create_gallery, create_photo, \
	remove_photo, remove_gallery, get_galleries, update_event_details, \
	update_user
	
from views import main, login, signup, help, galleries, events_view, \
	messages_widget, event_short_template, observer_profile, \
	organisator_profile, main_layout, logout

processed_partial_patterns = patterns('',
	url(r'^main$', main, name='main'),
	url(r'^login$', login, name='login'),
	url(r'^signup$', signup, name='signup'),
	url(r'^help$', help, name='help'),
	url(r'^galleries$', galleries, name='galleries'),
	url(r'^events_view$', events_view, name='events_view'),
	url(r'^messages_widget$', messages_widget, name='messages_widget'),
	url(r'^event_short_template$', event_short_template, name='event_short_template'),
	url(r'^profile/observer$', observer_profile, name='observer_profile'),
	url(r'^profile/organisator$', organisator_profile, name='organisator_profile'),
)

urlpatterns = i18n_patterns('',
	url(r'^$', main_layout, name='main_layout'),
	url(r'^messages/$', get_user_messages, name='user_messages'),
	url(r'^logout/$', logout, name='logout'),
	url(r'^processed_partials/', include(processed_partial_patterns, namespace='processed_partials')),
	url(r'^get_events/(?P<username>\w{1,50})/', get_events, name='get_events'),
	url(r'^get_all_events/', get_all_events, name='get_all_events'),
	url(r'^get_galleries/(?P<username>\w{1,50})/', get_galleries, name='get_galleries'),
	url(r'^remove_event/(?P<title>.*)/', remove_event, name='remove_event'),
	url(r'^remove_photo/(?P<id>\w{1,50})/', remove_photo, name='remove_photo'),
	url(r'^remove_gallery/(?P<id>\w{1,50})/', remove_gallery, name='remove_gallery'),
	url(r'^create_event/', create_event, name='create_event'),
	url(r'^create_gallery/', create_gallery, name='create_gallery'),
	url(r'^create_photo/', create_photo, name='create_photo'),
	url(r'^update_event_details/', update_event_details, name='update_event_details'),
	url(r'^update_user/', update_user, name='update_user'),
	(r'^photologue/', include('photologue_custom.urls')),
	url(r'^photologue/', include('photologue.urls', namespace='photologue')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "eventprowl.src.views.error404"

eventprowl/photologue/urls.py
from django.conf.urls import *
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from .views import PhotoListView, PhotoDetailView, GalleryListView, \
    GalleryDetailView, PhotoArchiveIndexView, PhotoDateDetailView, PhotoDayArchiveView, \
    PhotoYearArchiveView, PhotoMonthArchiveView, GalleryArchiveIndexView, GalleryYearArchiveView, \
    GalleryDateDetailView, GalleryDayArchiveView, GalleryMonthArchiveView, GalleryDateDetailOldView, \
    GalleryDayArchiveOldView, GalleryMonthArchiveOldView, PhotoDateDetailOldView, \
    PhotoDayArchiveOldView, PhotoMonthArchiveOldView

"""NOTE: the url names are changing. In the long term, I want to remove the 'pl-'
prefix on all urls, and instead rely on an application namespace 'photologue'.

At the same time, I want to change some URL patterns, e.g. for pagination. Changing the urls
twice within a few releases, could be confusing, so instead I am updating URLs bit by bit.

The new style will coexist with the existing 'pl-' prefix for a couple of releases.

"""


urlpatterns = patterns('',

                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           GalleryDateDetailView.as_view(month_format='%m'),
                           name='gallery-detail'),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
                           GalleryDayArchiveView.as_view(month_format='%m'),
                           name='gallery-archive-day'),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
                           GalleryMonthArchiveView.as_view(month_format='%m'),
                           name='gallery-archive-month'),
                       url(r'^gallery/(?P<year>\d{4})/$',
                           GalleryYearArchiveView.as_view(),
                           name='pl-gallery-archive-year'),
                       url(r'^gallery/$',
                           GalleryArchiveIndexView.as_view(),
                           name='pl-gallery-archive'),
                       url(r'^$',
                           RedirectView.as_view(url=reverse_lazy('photologue:pl-gallery-archive')),
                           name='pl-photologue-root'),
                       url(r'^gallery/(?P<slug>[\-\d\w]+)/$',
                           GalleryDetailView.as_view(), name='pl-gallery'),
                       url(r'^gallerylist/$',
                           GalleryListView.as_view(),
                           name='gallery-list'),

                       url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           PhotoDateDetailView.as_view(month_format='%m'),
                           name='photo-detail'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
                           PhotoDayArchiveView.as_view(month_format='%m'),
                           name='photo-archive-day'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
                           PhotoMonthArchiveView.as_view(month_format='%m'),
                           name='photo-archive-month'),
                       url(r'^photo/(?P<year>\d{4})/$',
                           PhotoYearArchiveView.as_view(),
                           name='pl-photo-archive-year'),
                       url(r'^photo/$',
                           PhotoArchiveIndexView.as_view(),
                           name='pl-photo-archive'),

                       url(r'^photo/(?P<slug>[\-\d\w]+)/$',
                           PhotoDetailView.as_view(),
                           name='pl-photo'),
                       url(r'^photolist/$',
                           PhotoListView.as_view(),
                           name='photo-list'),

                       # Deprecated URLs.
                       url(r'^gallery/page/(?P<page>[0-9]+)/$',
                           GalleryListView.as_view(),
                           {'deprecated_pagination': True},
                           name='pl-gallery-list'),
                       url(r'^photo/page/(?P<page>[0-9]+)/$',
                           PhotoListView.as_view(),
                           {'deprecated_pagination': True},
                           name='pl-photo-list'),

                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           GalleryDateDetailOldView.as_view(),
                           name='pl-gallery-detail'),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',
                           GalleryDayArchiveOldView.as_view(),
                           name='pl-gallery-archive-day'),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
                           GalleryMonthArchiveOldView.as_view(),
                           name='pl-gallery-archive-month'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           PhotoDateDetailOldView.as_view(),
                           name='pl-photo-detail'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',
                           PhotoDayArchiveOldView.as_view(),
                           name='pl-photo-archive-day'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
                           PhotoMonthArchiveOldView.as_view(),
                           name='pl-photo-archive-month')
                       )

eventprowl/photologue/views.py
import warnings

from django.conf import settings
from django.views.generic.dates import ArchiveIndexView, DateDetailView, DayArchiveView, MonthArchiveView, \
    YearArchiveView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse

from .models import Photo, Gallery

# Number of galleries to display per page.
GALLERY_PAGINATE_BY = getattr(settings, 'PHOTOLOGUE_GALLERY_PAGINATE_BY', 20)

if GALLERY_PAGINATE_BY != 20:
    warnings.warn(
        DeprecationWarning('PHOTOLOGUE_GALLERY_PAGINATE_BY setting will be removed in Photologue 3.2'))

# Number of photos to display per page.
PHOTO_PAGINATE_BY = getattr(settings, 'PHOTOLOGUE_PHOTO_PAGINATE_BY', 20)

if PHOTO_PAGINATE_BY != 20:
    warnings.warn(
        DeprecationWarning('PHOTOLOGUE_PHOTO_PAGINATE_BY setting will be removed in Photologue 3.2'))

# Gallery views.


class GalleryListView(ListView):
    queryset = Gallery.objects.on_site().is_public()
    paginate_by = GALLERY_PAGINATE_BY

    def get_context_data(self, **kwargs):
        context = super(GalleryListView, self).get_context_data(**kwargs)
        if self.kwargs.get('deprecated_pagination', False):
            warnings.warn(
                DeprecationWarning('Page numbers should now be passed via a page query-string parameter.'
                                   ' The old style "/page/n/"" will be removed in Photologue 3.2.'))
        return context


class GalleryDetailView(DetailView):
    queryset = Gallery.objects.on_site().is_public()


class GalleryDateView(object):
    queryset = Gallery.objects.on_site().is_public()
    date_field = 'date_added'
    allow_empty = True


class GalleryDateDetailView(GalleryDateView, DateDetailView):
    pass


class GalleryArchiveIndexView(GalleryDateView, ArchiveIndexView):
    pass


class GalleryDayArchiveView(GalleryDateView, DayArchiveView):
    pass


class GalleryMonthArchiveView(GalleryDateView, MonthArchiveView):
    pass


class GalleryYearArchiveView(GalleryDateView, YearArchiveView):
    make_object_list = True

# Photo views.


class PhotoListView(ListView):
    queryset = Photo.objects.on_site().is_public()
    paginate_by = PHOTO_PAGINATE_BY

    def get_context_data(self, **kwargs):
        context = super(PhotoListView, self).get_context_data(**kwargs)
        if self.kwargs.get('deprecated_pagination', False):
            warnings.warn(
                DeprecationWarning('Page numbers should now be passed via a page query-string parameter.'
                                   ' The old style "/page/n/"" will be removed in Photologue 3.2'))
        return context


class PhotoDetailView(DetailView):
    queryset = Photo.objects.on_site().is_public()


class PhotoDateView(object):
    queryset = Photo.objects.on_site().is_public()
    date_field = 'date_added'
    allow_empty = True


class PhotoDateDetailView(PhotoDateView, DateDetailView):
    pass


class PhotoArchiveIndexView(PhotoDateView, ArchiveIndexView):
    pass


class PhotoDayArchiveView(PhotoDateView, DayArchiveView):
    pass


class PhotoMonthArchiveView(PhotoDateView, MonthArchiveView):
    pass


class PhotoYearArchiveView(PhotoDateView, YearArchiveView):
    make_object_list = True


# Deprecated views.

class DeprecatedMonthMixin(object):

    """Representation of months in urls has changed from a alpha representation ('jan' for January)
    to a numeric representation ('01' for January).
    Properly deprecate the previous urls."""

    query_string = True

    month_names = {'jan': '01',
                   'feb': '02',
                   'mar': '03',
                   'apr': '04',
                   'may': '05',
                   'jun': '06',
                   'jul': '07',
                   'aug': '08',
                   'sep': '09',
                   'oct': '10',
                   'nov': '11',
                   'dec': '12', }

    def get_redirect_url(self, *args, **kwargs):
        print('a')
        warnings.warn(
            DeprecationWarning('Months are now represented in urls by numbers rather than by '
                               'their first 3 letters. The old style will be removed in Photologue 3.2.'))


class GalleryDateDetailOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(GalleryDateDetailOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:gallery-detail', kwargs={'year': kwargs['year'],
                                                            'month': self.month_names[kwargs['month']],
                                                            'day': kwargs['day'],
                                                            'slug': kwargs['slug']})


class GalleryDayArchiveOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(GalleryDayArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:gallery-archive-day', kwargs={'year': kwargs['year'],
                                                                 'month': self.month_names[kwargs['month']],
                                                                 'day': kwargs['day']})


class GalleryMonthArchiveOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(GalleryMonthArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:gallery-archive-month', kwargs={'year': kwargs['year'],
                                                                   'month': self.month_names[kwargs['month']]})


class PhotoDateDetailOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoDateDetailOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:photo-detail', kwargs={'year': kwargs['year'],
                                                          'month': self.month_names[kwargs['month']],
                                                          'day': kwargs['day'],
                                                          'slug': kwargs['slug']})


class PhotoDayArchiveOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoDayArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:photo-archive-day', kwargs={'year': kwargs['year'],
                                                               'month': self.month_names[kwargs['month']],
                                                               'day': kwargs['day']})


class PhotoMonthArchiveOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoMonthArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:photo-archive-month', kwargs={'year': kwargs['year'],
                                                                 'month': self.month_names[kwargs['month']]})

eventprowl/photologue/contrib/old_style_templates/templates/photologue/gallery_archive.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Latest Photo Galleries{% endblock %}

{% block content %}

<h1>Latest Photo Galleries</h1>

{% if latest %}
    {% for gallery in latest %}
    <div class="photo-gallery">
        <h2><a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a></h2>
        {% for photo in gallery.sample %}
        <div class="gallery-photo">
            <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" class="{% block gallery-photo-class %}{% endblock %}" alt="{{ photo.title }}"/></a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
{% else %}
    <p>No galleries were found.</p>
{% endif %}

<p><a href="{% url 'photologue:gallery-list' %}">View all galleries.</a></p>

{% endblock %}

eventprowl/photologue/contrib/old_style_templates/templates/photologue/gallery_archive_day.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Galleries for {{ day|date }}{% endblock %}

{% block content %}

<h1>Galleries for {{ day|date }}</h1>

{% if object_list %}
    {% for gallery in object_list %}
    <div class="photo-gallery">
        <h2>{{ gallery.title }}</h2>
        {% for photo in gallery.sample %}
        <div class="gallery-photo">
            <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
{% else %}
    <p>No galleries were found.</p>
{% endif %}

<p><a href="{% url 'photologue:gallery-list' %}">View all galleries.</a></p>

{% endblock %}

eventprowl/photologue/contrib/old_style_templates/templates/photologue/gallery_archive_month.html
w{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Galleries for {{ month|date:"F Y" }}{% endblock %}

{% block content %}

<h1>Galleries for {{ month|date:"F Y" }}</h1>

{% if object_list %}
    {% for gallery in object_list %}
    <div class="photo-gallery">
        <h2>{{ gallery.title }}</h2>
        {% for photo in gallery.sample %}
        <div class="gallery-photo">
            <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
{% else %}
    <p>No galleries were found.</p>
{% endif %}

<p><a href="{% url 'photologue:gallery-list' 1 %}">View all galleries.</a></p>

{% endblock %}

eventprowl/photologue/contrib/old_style_templates/templates/photologue/gallery_archive_year.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Galleries for {{ year }}{% endblock %}

{% block content %}

<h1>Galleries for {{ year }}</h1>
<ul>
{% for date in date_list %}
<li><a href="{{ date|date:"M"|lower }}/">{{ date|date:"F" }}</a></li>
{% endfor %}
</ul>

<p><a href="{% url 'photologue:gallery-list' %}">View all galleries.</a></p>

{% endblock %}

eventprowl/photologue/contrib/old_style_templates/templates/photologue/gallery_detail.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}

<h1>{{ object.title }}</h1>
<h2>Originally published {{ object.date_added|date:"l, F jS, Y" }}</h2>
{% if object.description %}<p>{{ object.description }}</p>{% endif %}
<div class="photo-gallery">
    {% for photo in object.public %}
    <div class="gallery-photo">
        <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" class="{% block gallery-photo-class %}{% endblock %}" alt="{{ photo.title }}"/></a>
    </div>
    {% endfor %}
</div>
<p><a href="{% url 'photologue:gallery-list' %}">View all galleries</a></p>

{% endblock %}

eventprowl/photologue/contrib/old_style_templates/templates/photologue/gallery_list.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}All Galleries{% endblock %}

{% block content %}

<h1>All galleries</h1>

{% if object_list %}
    {% for gallery in object_list %}
    <div class="photo-gallery">
        <h2><a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a></h2>
        {% for photo in gallery.sample %}
        <div class="gallery-photo">
            <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" class="{% block gallery-photo-class %}{% endblock %}" alt="{{ photo.title }}"/></a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
{% else %}
    <p>No galleries were found.</p>
{% endif %}

{% if is_paginated %}
<p>{{ page_obj.paginator.count }} galleries total.</p>
<div id="page_controls">
    <p>{% if page_obj.has_previous %}
    	<a href="{% url 'photologue:gallery-list' %}?page={{ page_obj.previous_page_number }}">Previous</a> | {% endif %} page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} {% if page_obj.has_next %}| <a href="{% url 'photologue:gallery-list' %}?page={{ page_obj.next_page_number }}">Next</a>{% endif %}
    </p>
</div>
{% endif %}

{% endblock %}

eventprowl/photologue/contrib/old_style_templates/templates/photologue/photo_archive.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Latest Photos{% endblock %}

{% block content %}

<h1>Latest Photos</h1>

{% if latest %}
    {% for photo in latest %}
    <div class="gallery-photo">
        <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
    </div>
    {% endfor %}
{% else %}
<p>No photos were found.</p>
{% endif %}
<p><a href="{% url 'photologue:photo-list' %}">View all photographs</a></p>

{% endblock %}

eventprowl/photologue/contrib/old_style_templates/templates/photologue/photo_archive_day.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Photos for {{ day|date }}{% endblock %}

{% block content %}

<h1>Photos for {{ day|date }}</h1>

{% if object_list %}
    {% for photo in object_list %}
    <div class="gallery-photo">
        <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
    </div>
    {% endfor %}
{% else %}
<p>No photos were found.</p>
{% endif %}
<p><a href="{% url 'photologue:photo-list' %}">View all photographs</a></p>

{% endblock %}

eventprowl/photologue/contrib/old_style_templates/templates/photologue/photo_archive_month.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Photos for {{ month|date:"F Y" }}{% endblock %}

{% block content %}

<h1>Photos for {{ month|date:"F Y" }}</h1>

{% if object_list %}
    {% for photo in object_list %}
    <div class="gallery-photo">
        <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
    </div>
    {% endfor %}
{% else %}
<p>No photos were found.</p>
{% endif %}
<p><a href="{% url 'photologue:photo-list' %}">View all photographs</a></p>

{% endblock %}

eventprowl/photologue/contrib/old_style_templates/templates/photologue/photo_archive_year.html
{% extends "photologue/root.html" %}

{% block title %}Galleries for {{ year }}{% endblock %}

{% block content %}

<h1>Photos for {{ year }}</h1>
<ul>
{% for date in date_list %}
<li><a href="{{ date|date:"M"|lower }}/">{{ date|date:"F" }}</a></li>
{% endfor %}
</ul>

{% endblock %}

eventprowl/photologue/contrib/old_style_templates/templates/photologue/photo_detail.html
{% extends "photologue/root.html" %}

{% load photologue_tags %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}

<h1>{{ object.title }}</h1>
<div class="gallery-photo">
    <a href="{{ object.image.url }}"><img src="{{ object.get_display_url }}" class="{% block gallery-photo-class %}{% endblock %}" alt="{{ object.title }}"/></a>
    {% if object.caption %}<p>{{ object.caption }}</p>{% endif %}
</div>
{% if object.public_galleries %}
<h2>This photo is found in the following galleries:</h2>
<ol>
{% for gallery in object.public_galleries %}
    <li>{%previous_in_gallery object gallery%} <a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a> {%next_in_gallery object gallery%}</li>
{% endfor %}
</ol>
{% endif %}

{% endblock %}

eventprowl/photologue/contrib/old_style_templates/templates/photologue/photo_list.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}All Photos{% endblock %}

{% block content %}

<h1>All Photos</h1>

{% if object_list %}
    {% for photo in object_list %}
    <div class="gallery-photo">
        <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
    </div>
    {% endfor %}
{% else %}
<p>No photos were found.</p>
{% endif %}

{% if is_paginated %}
<p>{{ paginator.count }} photos total.</p>
<div id="page_controls">
    <p>{% if page_obj.has_previous %}<a href="{% url 'photologue:photo-list' %}?page={{ page_obj.previous_page_number }}">Previous</a> | {% endif %} page {{ page_obj.number }} of {{ paginator.num_pages }} {% if page_obj.has_next %}| <a href="{% url 'photologue:photo-list' %}?page={{ page_obj.next_page_number }}">Next</a>{% endif %}</p>
</div>
{% endif %}

{% endblock %}

eventprowl/photologue/contrib/old_style_templates/templates/photologue/root.html
{% extends "base.html" %}